modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/malcolmriley/minecraft-library/issues"

[[mods]]
modId="paragon_library"
version="${file.jarVersion}"
displayName="The Paragon's Stash"
logoFile="logo.png"
credits="The_Paragon"
authors="Malcolm Riley"
description='''
Yes, you guessed it, it's yet another library mod. This time it's for The_Paragon's various mods.
'''

[[dependencies.TEMPLATE]]
    modId="forge"
    mandatory=true
    versionRange="[40.1,)"
    ordering="NONE"
    side="BOTH"
